### ISSUE TITLE
Couldn't connect to either BHv1 or BHv2

### ISSUE THREAD

**Issue by andrade** [intel/dynamic-application-loader-host-interface#5] opened 2017-07-06 16:32 UTC
The JHI service appears to start fine but once I restart AESMD I get the following errors related to JHI:

```
systemd[1]: Started Intel Dynamic Application Loader Host Interface (JHI).

(...)

jhi[9634]: Error: discoverVmType() failed
jhi[9634]: JHI init failed
jhi[9634]: JHI service release prints are enabled
jhi[9634]: AppletsManager::discoverVmType(), Couldn't connect to either BHv1 or BHv2.
jhi[9634]: Error: discoverVmType() failed
jhi[9634]: JHI init failed
jhi[9634]: JHI service release prints are enabled
jhi[9634]: AppletsManager::discoverVmType(), Couldn't connect to either BHv1 or BHv2.
jhi[9634]: Error: discoverVmType() failed
jhi[9634]: JHI init failed

(...)

jhi[9678]: JHI init at server side failed
jhi[9678]: JHI init failed. Status: 768
aesm_service[9678]: [ADMIN]Platform Services initializing
aesm_service[9678]: [ADMIN]Platform Services initialization failed due to DAL error
```

The OS is Ubuntu 16.04.

**Comment by light1021** [comment] 2017-07-10 07:22
I meet this error too. Is there anyone who can tell me the reason. thanks

**Comment by jlahav** [comment] 2017-07-10 07:45
Hi. The error "Couldn't connect to either BHv1 or BHv2" means that JHI tried to connect to DAL FW but failed. This can be caused by a wrong configuration (unlikely since you say it worked before), bad mei kernel module state or bad FW state. It can also happen if another process in the system holds the DAL FW connection.

The first step in trying to understand what went wrong is to find what helps recover from this state. Does JHI restart help? If you stop JHI, can you see another instance of it running? What happens if you close all instances of the JHI process and then start one?

**Comment by light1021** [comment] 2017-07-10 08:58
@jlahav Thank you. There is only one instance. If I just restart JHI, it seems everything is ok. But when I restart aesmd after jhi started up, JHI again reports that error.

**Comment by jlahav** [comment] 2017-07-10 12:13
I created a working setup with JHI and AESMD. Tested JHI - works. Restarted AESMD and tested JHI again - works.

This is my setup:
Ubuntu 16.04 64 bit over SKL.

Can you think of a difference between out setups that makes it work here and fail on your side?
Also, if you could attach the log of JHI from the moment of restarting AESMD, not only from afterwards, it might help.

**Comment by light1021** [comment] 2017-07-11 01:44
I have three devices a server  with S1200SP board, a Intel NUC， and a dell xps，both of them have ubuntu 16.04.2 installed. I set up sgx development environment for all. But this only happened  on the server. I find 
that /dev/mei is missing. How can I solve this ?

**Comment by jlahav** [comment] 2017-07-11 11:25
Ok. It's starting to make sense.
S1200SP is a family of boards. Which one is yours?
https://ark.intel.com/products/series/89096/Intel-Server-Board-S1200SP-Family
Some of these have DAL and some don't.
Check the field "Board Chipset" for your board.
This is an example for a chipset I expect to work: https://ark.intel.com/products/90594/Intel-C236-Chipset because it has the line "Intel® ME Firmware Version 11.0".
This is an example of a chipset that I don't expect to work: https://ark.intel.com/products/90578/Intel-C232-Chipset

By the way, has it ever worked on the server? You can observe normal operation of JHI on the other computers by enabling debug prints in /etc/jhi/jhi.conf and comparing with the logs on the server (restart JHI after a change).

**Comment by andrade** [comment] 2017-07-11 14:25
Hi. My board is [Supermicro X11SSH-F](https://www.supermicro.com/products/motherboard/Xeon/C236_C232/X11SSH-F.cfm) and the chipset appears to be Intel C236.

I have the same behavior as light1021: when I restart JHI everything seems okay, but when I restart AESMD then JHI reports errors.

`lsmod` shows mei, but I do not have the device `/dev/mei0`.

```
$ lsmod | grep mei
mei_me                 36864  0
mei                    98304  1 mei_me
```

# LOGS

I enabled debug prints in /etc/jhi/jhi.conf, and restarted JHI followed by AESMD with following commands (attached corresponding log from syslog):

```
$ sudo vim /etc/jhi/jhi.conf
$ sudo service jhi restart
$ sudo service jhi status
● jhi.service - Intel Dynamic Application Loader Host Interface (JHI)
   Loaded: loaded (/lib/systemd/system/jhi.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-07-11 15:13:35 WEST; 3s ago
  Process: 2860 ExecStart=/usr/sbin/jhid -d (code=exited, status=0/SUCCESS)
 Main PID: 2862 (jhid)
   CGroup: /system.slice/jhi.service
           └─2862 /usr/sbin/jhid -d

Jul 11 15:13:35 NODE systemd[1]: Starting Intel Dynamic Application Loader Host Interface (JHI)...
Jul 11 15:13:35 NODE jhi[2862]: --> jhi start
Jul 11 15:13:35 NODE jhi[2862]: <-- jhi start
Jul 11 15:13:35 NODE systemd[1]: Started Intel Dynamic Application Loader Host Interface (JHI).
$ sudo service aesmd restart
$ sudo service aesmd status
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-07-11 15:13:49 WEST; 4s ago
  Process: 2891 ExecStart=/opt/intel/sgxpsw/aesm/aesm_service (code=exited, status=0/SUCCESS)
 Main PID: 2893 (aesm_service)
   CGroup: /system.slice/aesmd.service
           └─2893 /opt/intel/sgxpsw/aesm/aesm_service

Jul 11 15:13:49 NODE jhi[2893]: JHI init at server side failed
Jul 11 15:13:49 NODE jhi[2893]: JHI init failed. Status: 768
Jul 11 15:13:49 NODE jhi[2893]: JHI client - debug trace and release prints are enabled
Jul 11 15:13:49 NODE jhi[2893]: JHI init at server side failed
Jul 11 15:13:49 NODE jhi[2893]: JHI init failed. Status: 768
Jul 11 15:13:49 NODE jhi[2893]: JHI client - debug trace and release prints are enabled
Jul 11 15:13:49 NODE jhi[2893]: JHI init at server side failed
Jul 11 15:13:49 NODE jhi[2893]: JHI init failed. Status: 768
Jul 11 15:13:49 NODE aesm_service[2893]: [ADMIN]Platform Services initializing
Jul 11 15:13:49 NODE aesm_service[2893]: [ADMIN]Platform Services initialization failed due to DAL error
$ sudo service jhi status
● jhi.service - Intel Dynamic Application Loader Host Interface (JHI)
   Loaded: loaded (/lib/systemd/system/jhi.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-07-11 15:13:35 WEST; 26s ago
  Process: 2860 ExecStart=/usr/sbin/jhid -d (code=exited, status=0/SUCCESS)
 Main PID: 2862 (jhid)
   CGroup: /system.slice/jhi.service
           └─2862 /usr/sbin/jhid -d

Jul 11 15:13:49 NODE jhi[2862]: JHI init failed
Jul 11 15:13:49 NODE jhi[2862]: JHI service debug trace and release prints are enabled
Jul 11 15:13:49 NODE jhi[2862]: GlobalsManager - setAppletsFolder = /var/lib/intel/dal/applet_repository
Jul 11 15:13:49 NODE jhi[2862]: GlobalsManager - setServiceFolder = /usr/sbin
Jul 11 15:13:49 NODE jhi[2862]: Using transport type: 2
Jul 11 15:13:49 NODE jhi[2862]: GlobalsManager - setTransportType = 2.
Jul 11 15:13:49 NODE jhi[2862]: Starting VM type discovery...
Jul 11 15:13:49 NODE jhi[2862]: AppletsManager::discoverVmType(), Couldn't connect to either BHv1 or BHv2.
Jul 11 15:13:49 NODE jhi[2862]: Error: discoverVmType() failed
Jul 11 15:13:49 NODE jhi[2862]: JHI init failed
```

[log-170711-1520-JHI-LogDebugLevel.txt](https://github.com/01org/dynamic-application-loader-host-interface/files/1139158/log-170711-1520-JHI-LogDebugLevel.txt)

**Comment by jlahav** [comment] 2017-07-11 14:42
No idea yet but for now just a little correction. When JHI starts it doesn't do anything apart from listening to requests. When the first request comes it tries to connect to the FW for the first time. Restarting AESMD probably sends a request to JHI, which causes the FW connection attempt, which fails.
The fact that there is no error prior to the AESMD restart doesn't mean that everything was OK, it just means that nothing happened yet.

Now, about the question, I'll see if I can find a way to check whether DAL is present on such computer or not.

**Comment by jlahav** [comment] 2017-07-12 07:54
So, mei lists the available FW connections, each has a unique identifier. If DAL is available, its identifier will be listed in /sys/kernel/debug/mei0/meclients (might be mei, and you need to be root to access the file).
See if you have an ID ending in C1AA440E. If it's not there, DAL is not available.

**Comment by andrade** [comment] 2017-07-12 09:12
The server doesn't have any directory under /sys/kernel/debug/ with mei or mei0 in the name.

I have it in my laptop, but it doesn't support SGX in hardware mode (broadwell CPU).

```
$ sudo more /sys/kernel/debug/mei0/meclients | grep -i C1AA440E
 2|38|  0|3c4852d6-d47b-4f46-b05e-b5edc1aa440e|  1|   4096| 0|   3|
```

Guess I'm out of luck, thank you for your help, @jlahav.

A final question. The server motherboard I'm using does not support Intel AMT. Do you know if support for Intel AMT is a requirement for having a functional mei and for DAL to work?

**Comment by light1021** [comment] 2017-07-12 10:37
I fond my Motherboard is S1200SPO which has [C236 chipset](https://ark.intel.com/products/88264/Intel-Server-Board-S1200SPO)
`(v01 INTEL  S1200SPO 00000000 INTL 01000013)`.

As you described, It should work, but ...

**Comment by skochinsky** [comment] 2017-07-12 18:07
> The server motherboard I'm using does not support Intel AMT. Do you know if support for Intel AMT is a requirement for having a functional mei and for DAL to work?

AFAIK AMT is _not_ required, but the ME (or SpS) firmware needs to include the DAL component (it's quite possible that the server firmwares don't include it). For the mei driver, it's possible that the mainline driver is missing the PCI IDs specific to your chipset. You can try getting the HECI/MEI device ID via `lspci` and adjusting the driver source to include them similar to [this](https://github.com/torvalds/linux/commit/9ff2007bea1f1bfc53ac0bc7ccf8200bb275fd52).

**Comment by andrade** [comment] 2017-07-12 18:38
Thank you, @skochinsky. The IDs should already be present so I'm not sure there's anything I can do. They are the first two in the link you posted:
```
#define MEI_DEV_ID_SPT_H      0xA13A  /* Sunrise Point H */
#define MEI_DEV_ID_SPT_H_2    0xA13B  /* Sunrise Point H 2 */
```

The output in my machine:
```
$ sudo lspci -nn | grep -i HECI
00:16.0 Communication controller [0780]: Intel Corporation Sunrise Point-H CSME HECI #1 [8086:a13a] (rev 31)
00:16.1 Communication controller [0780]: Intel Corporation Sunrise Point-H CSME HECI #2 [8086:a13b] (rev 31)
```

**Comment by skochinsky** [comment] 2017-07-12 18:42
Then I can only suggest trying to add some debug prints to the module and see why it refuses to load after `modprobe`/`insmod` (or maybe there are already some messages in the kernel log).

**Comment by andrade** [comment] 2017-07-12 19:14
The errors I get in syslog are `Couldn't stat device /dev/mei0` and then `kernel: [633387.561876] isgx: [10774:0x00007f5b1e500000] EINIT returned 2`. This happens when I restart aesmd.

1. I suppose the stat failure is because the driver is not loaded. (modprobe does nothing)
2. The isgx error is [already reported](https://github.com/01org/linux-sgx/issues/44#issuecomment-275245927) and appears to be benign.

**Comment by tomasbw** [comment] 2017-07-13 08:48
Intel servers are running a different type of firmware (SPS), and not all of them supports  MEI protocol and hence doesn't run JHI as well.  MEI driver detects SPS firmware and just bails out. 
You can post your 'sudo lspci -vnxx' dump we can check that SPS presents from the pci config space.

**Comment by andrade** [comment] 2017-07-13 08:58
Here's the output of `sudo lspci -vnxx`:

```
00:00.0 0600: 8086:1918 (rev 07)
	Subsystem: 15d9:0884
	Flags: bus master, fast devsel, latency 0
	Capabilities: [e0] Vendor Specific Information: Len=10 <?>
	Kernel driver in use: ie31200_edac
	Kernel modules: ie31200_edac
00: 86 80 18 19 06 00 90 20 07 00 00 06 00 00 00 00
10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 84 08
30: 00 00 00 00 e0 00 00 00 00 00 00 00 00 00 00 00

00:13.0 0000: 8086:a135 (rev 31)
	Flags: fast devsel, IRQ 11
	Memory at df322000 (64-bit, non-prefetchable) [disabled] [size=4K]
	Capabilities: [80] Power Management version 3
00: 86 80 35 a1 00 00 10 00 31 00 00 00 00 00 00 00
10: 04 20 32 df 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
30: 00 00 00 00 80 00 00 00 00 00 00 00 0b 01 00 00

00:14.0 0c03: 8086:a12f (rev 31) (prog-if 30 [XHCI])
	Subsystem: 15d9:0884
	Flags: bus master, medium devsel, latency 0, IRQ 28
	Memory at df300000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: [70] Power Management version 2
	Capabilities: [80] MSI: Enable+ Count=1/8 Maskable- 64bit+
	Kernel driver in use: xhci_hcd
00: 86 80 2f a1 06 04 90 02 31 30 03 0c 00 00 80 00
10: 04 00 30 df 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 84 08
30: 00 00 00 00 70 00 00 00 00 00 00 00 0b 01 00 00

00:14.2 1180: 8086:a131 (rev 31)
	Subsystem: 15d9:0884
	Flags: fast devsel, IRQ 11
	Memory at df321000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: [50] Power Management version 3
	Capabilities: [80] MSI: Enable- Count=1/1 Maskable- 64bit-
00: 86 80 31 a1 02 00 10 00 31 00 80 11 00 00 00 00
10: 04 10 32 df 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 84 08
30: 00 00 00 00 50 00 00 00 00 00 00 00 0b 03 00 00

00:16.0 0780: 8086:a13a (rev 31)
	Subsystem: 15d9:0884
	Flags: bus master, fast devsel, latency 0, IRQ 11
	Memory at df320000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: [50] Power Management version 3
	Capabilities: [8c] MSI: Enable- Count=1/1 Maskable- 64bit+
	Kernel modules: mei_me
00: 86 80 3a a1 06 00 10 00 31 00 80 07 00 00 80 00
10: 04 00 32 df 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 84 08
30: 00 00 00 00 50 00 00 00 00 00 00 00 0b 01 00 00

00:16.1 0780: 8086:a13b (rev 31)
	Subsystem: 15d9:0884
	Flags: bus master, fast devsel, latency 0, IRQ 11
	Memory at df31f000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: [50] Power Management version 3
	Capabilities: [8c] MSI: Enable- Count=1/1 Maskable- 64bit+
	Kernel modules: mei_me
00: 86 80 3b a1 06 00 10 00 31 00 80 07 00 00 80 00
10: 04 f0 31 df 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 84 08
30: 00 00 00 00 50 00 00 00 00 00 00 00 0b 01 00 00

00:17.0 0106: 8086:a102 (rev 31) (prog-if 01 [AHCI 1.0])
	Subsystem: 15d9:0884
	Flags: bus master, 66MHz, medium devsel, latency 0, IRQ 29
	Memory at df310000 (32-bit, non-prefetchable) [size=8K]
	Memory at df31e000 (32-bit, non-prefetchable) [size=256]
	I/O ports at f050 [size=8]
	I/O ports at f040 [size=4]
	I/O ports at f020 [size=32]
	Memory at df31d000 (32-bit, non-prefetchable) [size=2K]
	Capabilities: [80] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [70] Power Management version 3
	Capabilities: [a8] SATA HBA v1.0
	Kernel driver in use: ahci
	Kernel modules: ahci
00: 86 80 02 a1 07 04 b0 02 31 01 06 01 00 00 00 00
10: 00 00 31 df 00 e0 31 df 51 f0 00 00 41 f0 00 00
20: 21 f0 00 00 00 d0 31 df 00 00 00 00 d9 15 84 08
30: 00 00 00 00 80 00 00 00 00 00 00 00 0b 01 00 00

00:1c.0 0604: 8086:a110 (rev f1) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 25
	Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
	I/O behind bridge: 0000e000-0000efff
	Memory behind bridge: df200000-df2fffff
	Capabilities: [40] Express Root Port (Slot+), MSI 00
	Capabilities: [80] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [90] Subsystem: 15d9:0884
	Capabilities: [a0] Power Management version 3
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Access Control Services
	Capabilities: [220] #19
	Kernel driver in use: pcieport
	Kernel modules: shpchp
00: 86 80 10 a1 07 04 10 00 f1 00 04 06 00 00 81 00
10: 00 00 00 00 00 00 00 00 00 01 01 00 e0 e0 00 20
20: 20 df 20 df f1 ff 01 00 00 00 00 00 00 00 00 00
30: 00 00 00 00 40 00 00 00 00 00 00 00 0b 01 10 00

00:1c.1 0604: 8086:a111 (rev f1) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 26
	Bus: primary=00, secondary=02, subordinate=02, sec-latency=0
	I/O behind bridge: 0000d000-0000dfff
	Memory behind bridge: df100000-df1fffff
	Capabilities: [40] Express Root Port (Slot+), MSI 00
	Capabilities: [80] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [90] Subsystem: 15d9:0884
	Capabilities: [a0] Power Management version 3
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Access Control Services
	Capabilities: [220] #19
	Kernel driver in use: pcieport
	Kernel modules: shpchp
00: 86 80 11 a1 07 04 10 00 f1 00 04 06 00 00 81 00
10: 00 00 00 00 00 00 00 00 00 02 02 00 d0 d0 00 20
20: 10 df 10 df f1 ff 01 00 00 00 00 00 00 00 00 00
30: 00 00 00 00 40 00 00 00 00 00 00 00 0a 02 10 00

00:1c.6 0604: 8086:a116 (rev f1) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 27
	Bus: primary=00, secondary=03, subordinate=04, sec-latency=0
	I/O behind bridge: 0000c000-0000cfff
	Memory behind bridge: de000000-df0fffff
	Capabilities: [40] Express Root Port (Slot+), MSI 00
	Capabilities: [80] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [90] Subsystem: 15d9:0884
	Capabilities: [a0] Power Management version 3
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Access Control Services
	Capabilities: [220] #19
	Kernel driver in use: pcieport
	Kernel modules: shpchp
00: 86 80 16 a1 07 04 10 00 f1 00 04 06 00 00 81 00
10: 00 00 00 00 00 00 00 00 00 03 04 00 c0 c0 00 20
20: 00 de 00 df f1 ff 01 00 00 00 00 00 00 00 00 00
30: 00 00 00 00 40 00 00 00 00 00 00 00 0b 03 18 00

00:1f.0 0601: 8086:a149 (rev 31)
	Subsystem: 15d9:0884
	Flags: bus master, medium devsel, latency 0
00: 86 80 49 a1 07 00 00 02 31 00 01 06 00 00 80 00
10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 84 08
30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

00:1f.2 0580: 8086:a121 (rev 31)
	Subsystem: 15d9:0884
	Flags: fast devsel
	Memory at df318000 (32-bit, non-prefetchable) [disabled] [size=16K]
00: 86 80 21 a1 00 00 00 00 31 00 80 05 00 00 80 00
10: 00 80 31 df 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 84 08
30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

00:1f.4 0c05: 8086:a123 (rev 31)
	Subsystem: 15d9:0884
	Flags: medium devsel, IRQ 11
	Memory at df31c000 (64-bit, non-prefetchable) [size=256]
	I/O ports at f000 [size=32]
	Kernel modules: i2c_i801
00: 86 80 23 a1 03 00 80 02 31 00 05 0c 00 00 00 00
10: 04 c0 31 df 00 00 00 00 00 00 00 00 00 00 00 00
20: 01 f0 00 00 00 00 00 00 00 00 00 00 d9 15 84 08
30: 00 00 00 00 00 00 00 00 00 00 00 00 0b 01 00 00

01:00.0 0200: 8086:1533 (rev 03)
	DeviceName:  Intel Ethernet i210 #1
	Subsystem: 15d9:1533
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at df200000 (32-bit, non-prefetchable) [size=512K]
	I/O ports at e000 [size=32]
	Memory at df280000 (32-bit, non-prefetchable) [size=16K]
	Capabilities: [40] Power Management version 3
	Capabilities: [50] MSI: Enable- Count=1/1 Maskable+ 64bit+
	Capabilities: [70] MSI-X: Enable+ Count=5 Masked-
	Capabilities: [a0] Express Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Device Serial Number 0c-c4-7a-ff-ff-98-50-1c
	Capabilities: [1a0] Transaction Processing Hints
	Kernel driver in use: igb
	Kernel modules: igb
00: 86 80 33 15 07 04 10 00 03 00 00 02 00 00 00 00
10: 00 00 20 df 00 00 00 00 01 e0 00 00 00 00 28 df
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 33 15
30: 00 00 00 00 40 00 00 00 00 00 00 00 0b 01 00 00

02:00.0 0200: 8086:1533 (rev 03)
	DeviceName:  Intel Ethernet i210 #2
	Subsystem: 15d9:1533
	Flags: bus master, fast devsel, latency 0, IRQ 17
	Memory at df100000 (32-bit, non-prefetchable) [size=512K]
	I/O ports at d000 [size=32]
	Memory at df180000 (32-bit, non-prefetchable) [size=16K]
	Capabilities: [40] Power Management version 3
	Capabilities: [50] MSI: Enable- Count=1/1 Maskable+ 64bit+
	Capabilities: [70] MSI-X: Enable+ Count=5 Masked-
	Capabilities: [a0] Express Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Device Serial Number 0c-c4-7a-ff-ff-98-50-1d
	Capabilities: [1a0] Transaction Processing Hints
	Kernel driver in use: igb
	Kernel modules: igb
00: 86 80 33 15 07 04 10 00 03 00 00 02 00 00 00 00
10: 00 00 10 df 00 00 00 00 01 d0 00 00 00 00 18 df
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 33 15
30: 00 00 00 00 40 00 00 00 00 00 00 00 0a 01 00 00

03:00.0 0604: 1a03:1150 (rev 03) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0
	Bus: primary=03, secondary=04, subordinate=04, sec-latency=32
	I/O behind bridge: 0000c000-0000cfff
	Memory behind bridge: de000000-df0fffff
	Capabilities: [50] MSI: Enable- Count=1/1 Maskable- 64bit+
	Capabilities: [78] Power Management version 3
	Capabilities: [80] Express PCI-Express to PCI/PCI-X Bridge, MSI 00
	Capabilities: [a4] Subsystem: 15d9:0884
	Capabilities: [100] Virtual Channel
	Capabilities: [800] Advanced Error Reporting
	Kernel modules: shpchp
00: 03 1a 50 11 07 00 10 00 03 00 04 06 00 00 01 00
10: 00 00 00 00 00 00 00 00 03 04 04 20 c1 c1 20 02
20: 00 de 00 df f1 ff 01 00 00 00 00 00 00 00 00 00
30: 00 00 00 00 50 00 00 00 00 00 00 00 00 00 18 00

04:00.0 0300: 1a03:2000 (rev 30) (prog-if 00 [VGA controller])
	DeviceName:  ASPEED Video AST2400
	Subsystem: 15d9:0884
	Flags: bus master, medium devsel, latency 0, IRQ 18
	Memory at de000000 (32-bit, non-prefetchable) [size=16M]
	Memory at df000000 (32-bit, non-prefetchable) [size=128K]
	I/O ports at c000 [size=128]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: [40] Power Management version 3
	Capabilities: [50] MSI: Enable- Count=1/4 Maskable- 64bit+
	Kernel driver in use: ast
	Kernel modules: ast
00: 03 1a 00 20 07 00 10 02 30 00 00 03 00 00 00 00
10: 00 00 00 de 00 00 00 df 01 c0 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 84 08
30: 00 00 00 00 40 00 00 00 00 00 00 00 0b 01 00 00
```

**Comment by tomasbw** [comment] 2017-07-13 09:02
It missing offset 40, need another 'x'
sudo lspci -vnxxx -s 00:16.0

**Comment by andrade** [comment] 2017-07-13 09:04
```
$ sudo lspci -vnxxx -s 00:16.0
00:16.0 0780: 8086:a13a (rev 31)
	Subsystem: 15d9:0884
	Flags: bus master, fast devsel, latency 0, IRQ 11
	Memory at df320000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: [50] Power Management version 3
	Capabilities: [8c] MSI: Enable- Count=1/1 Maskable- 64bit+
	Kernel modules: mei_me
00: 86 80 3a a1 06 00 10 00 31 00 80 07 00 00 80 00
10: 04 00 32 df 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 d9 15 84 08
30: 00 00 00 00 50 00 00 00 00 00 00 00 0b 01 00 00
40: 45 03 0f 00 00 00 01 80 06 28 11 88 00 00 00 00
50: 01 8c 03 40 08 00 00 00 00 00 00 00 00 00 00 00
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
80: 00 00 00 00 00 00 00 00 00 00 00 00 05 00 80 00
90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40
c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
f0: 00 00 00 00 00 00 00 00 b3 0f 40 08 00 00 00 00
```

**Comment by light1021** [comment] 2017-07-13 09:09
`
00:16.0 0780: 8086:a13a (rev 31)
	Subsystem: 8086:1999
	Flags: fast devsel, IRQ 11
	Memory at 9ed17000 (64-bit, non-prefetchable) [disabled] [size=4K]
	Capabilities: [50] Power Management version 3
	Capabilities: [8c] MSI: Enable- Count=1/1 Maskable- 64bit+
	Kernel modules: mei_me
00: 86 80 3a a1 00 00 10 00 31 00 80 07 00 00 80 00
10: 04 70 d1 9e 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 86 80 99 19
30: 00 00 00 00 50 00 00 00 00 00 00 00 0b 01 00 00
40: 45 03 0f 00 00 00 01 80 06 a8 11 89 00 00 00 00
50: 01 8c 03 40 08 00 00 00 00 00 00 00 00 00 00 00
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
80: 00 00 00 00 00 00 00 00 00 00 00 00 05 00 80 00
90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40
c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
f0: 00 00 00 00 00 00 00 00 b3 0f 40 08 00 00 00 00
`
This is mine

**Comment by light1021** [comment] 2017-07-13 09:10
`00:16.0 0780: 8086:a13a (rev 31)
	Subsystem: 8086:1999
	Flags: fast devsel, IRQ 11
	Memory at 9ed17000 (64-bit, non-prefetchable) [disabled] [size=4K]
	Capabilities: [50] Power Management version 3
	Capabilities: [8c] MSI: Enable- Count=1/1 Maskable- 64bit+
	Kernel modules: mei_me
00: 86 80 3a a1 00 00 10 00 31 00 80 07 00 00 80 00
10: 04 70 d1 9e 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 86 80 99 19
30: 00 00 00 00 50 00 00 00 00 00 00 00 0b 01 00 00
40: 45 03 0f 00 00 00 01 80 06 a8 11 89 00 00 00 00
50: 01 8c 03 40 08 00 00 00 00 00 00 00 00 00 00 00
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
80: 00 00 00 00 00 00 00 00 00 00 00 00 05 00 80 00
90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40
c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
f0: 00 00 00 00 00 00 00 00 b3 0f 40 08 00 00 00 00`
This is mine.

**Comment by skochinsky** [comment] 2017-07-13 09:17
https://patchwork.kernel.org/patch/9454119/ looks like MEI driver specifically ignores SPS firmwares. and as I mentioned before, it's probably missing DAL anyway so this project is likely useless to you in any case.

**Comment by light1021** [comment] 2017-07-13 09:37
@jlahav @skochinsky @ @tomasbw 
Thank you anyway!

**Comment by andrade** [comment] 2017-07-13 09:41
Thank you. For my part the issue can be closed.

**Comment by tomasbw** [comment] 2017-07-13 09:45
40: 45 03 0f 00
00 00 0f 00
This is the SPS mask

**Comment by jlahav** [comment] 2017-07-13 10:08
Thanks everyone for the help. Closing.

**Closed as completed by jlahav** 2017-07-13 10:08 UTC
